### ISSUE TITLE
maxClientCnxns support in Docker image 

### ISSUE THREAD

**Issue by jmarcos-cano** [31z4/zookeeper-docker#18] opened 2017-08-24 00:19 UTC
Hey there, looking at docker-entrypoint.sh (which is the entrypoint of your zookeeper:3.4 image)

I see that it only support some of the configurations:

```
 Generate the config only if it doesn't exist
if [ ! -f "$ZOO_CONF_DIR/zoo.cfg" ]; then
    CONFIG="$ZOO_CONF_DIR/zoo.cfg"

    echo "clientPort=$ZOO_PORT" >> "$CONFIG"
    echo "dataDir=$ZOO_DATA_DIR" >> "$CONFIG"
    echo "dataLogDir=$ZOO_DATA_LOG_DIR" >> "$CONFIG"

    echo "tickTime=$ZOO_TICK_TIME" >> "$CONFIG"
    echo "initLimit=$ZOO_INIT_LIMIT" >> "$CONFIG"
    echo "syncLimit=$ZOO_SYNC_LIMIT" >> "$CONFIG"

    for server in $ZOO_SERVERS; do
        echo "$server" >> "$CONFIG"
    done
fi
```

but not all of them, is there any way to make this script a bit more smart in order to support: maxClientCnxns for example?

[confluentinc/kafka](https://github.com/confluentinc/kafka) has a good example of it.

**Comment by 31z4** [comment] 2017-08-24 09:41
Hi @jmarcos-cano. I do not plan to cover all Zookeeper configuration parameters. But `maxClientCnxns` has been requested [before](https://github.com/31z4/zookeeper-docker/issues/9). I think this time I'll find some time to implement it. For comprehensive configuration please either mount a config as a volume or `COPY` it within an image.

**Comment by 31z4** [comment] 2017-09-08 16:27
Duplicate of #9

**Closed by 31z4** 2017-09-08 16:27 UTC
